apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: doctors-container
        image: msk2k1/doctors-microservice:v1.0.1
        ports:
        - containerPort: 9090
          name: tcp
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /doctors
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1