apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-liveness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: doctors-container
        image: msk2k1/doctors-microservice:v1.0.1
        livenessProbe:
          httpGet:
            path: /doctors
            port: 9090
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3