apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: frontend-container
        image: msk2k1/frontend-microservice:v1.0.2
        ports:
        - containerPort: 3000
          name: tcp
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/appointments
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1