apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      app: microservice
  template:
    metadata:
      labels:
        tier: backend
        app: microservice
    spec:
      containers:
      - name: doctors
        image: msk2k1/doctors-microservice:v1.0.1

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        ports:
        - containerPort: 9090
          name: tcp

---
apiVersion: v1
kind: Service
metadata:
  name: doctors
spec:
  selector:
    tier: backend
    app: microservice
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090